In [1]:
## load the packages here
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
import matplotlib.pyplot as plt
import seaborn as sns
import csv
import regex as re
import statsmodels.api as sm

## Download your data and load them into the Python.
You can find them [**here**](https://drive.google.com/file/d/0Bz9_0VdXvv9bX0MzUEhVdmpCc3c/view?usp=sharing).

- Features and response variables are in different files
- be careful about number of spaces between the values in the file

In [2]:
# little help from us
parameters = []
with open('X_train.txt') as inputfile:
    for row in csv.reader(inputfile):
        parameters.append([float(i) for i in re.sub("\s+",",",row[0].strip()).split(",")])

In [3]:
X = pd.DataFrame(parameters)
X

0         1         2         3         4         5         6    \
0     0.288585 -0.020294 -0.132905 -0.995279 -0.983111 -0.913526 -0.995112   
1     0.278419 -0.016411 -0.123520 -0.998245 -0.975300 -0.960322 -0.998807   
2     0.279653 -0.019467 -0.113462 -0.995380 -0.967187 -0.978944 -0.996520   
3     0.279174 -0.026201 -0.123283 -0.996091 -0.983403 -0.990675 -0.997099   
4     0.276629 -0.016570 -0.115362 -0.998139 -0.980817 -0.990482 -0.998321   
...        ...       ...       ...       ...       ...       ...       ...   
7347  0.299665 -0.057193 -0.181233 -0.195387  0.039905  0.077078 -0.282301   
7348  0.273853 -0.007749 -0.147468 -0.235309  0.004816  0.059280 -0.322552   
7349  0.273387 -0.017011 -0.045022 -0.218218 -0.103822  0.274533 -0.304515   
7350  0.289654 -0.018843 -0.158281 -0.219139 -0.111412  0.268893 -0.310487   
7351  0.351503 -0.012423 -0.203867 -0.269270 -0.087212  0.177404 -0.377404   

           7         8         9    ...       551       552       553  \
0    -0.983185 -0.923527 -0.934724  ... -0.074323 -0.298676 -0.710304   
1    -0.974914 -0.957686 -0.943068  ...  0.158075 -0.595051 -0.861499   
2    -0.963668 -0.977469 -0.938692  ...  0.414503 -0.390748 -0.760104   
3    -0.982750 -0.989302 -0.938692  ...  0.404573 -0.117290 -0.482845   
4    -0.979672 -0.990441 -0.942469  ...  0.087753 -0.351471 -0.699205   
...        ...       ...       ...  ...       ...       ...       ...   
7347  0.043616  0.060410  0.210795  ... -0.070157 -0.588433 -0.880324   
7348 -0.029456  0.080585  0.117440  ...  0.165259 -0.390738 -0.680744   
7349 -0.098913  0.332584  0.043999  ...  0.195034  0.025145 -0.304029   
7350 -0.068200  0.319473  0.101702  ...  0.013865  0.063907 -0.344314   
7351 -0.038678  0.229430  0.269013  ... -0.058402 -0.387052 -0.740738   

           554       555       556       557       558       559       560  
0    -0.112754  0.030400 -0.464761 -0.018446 -0.841247  0.179941 -0.058627  
1     0.053477 -0.007435 -0.732626  0.703511 -0.844788  0.180289 -0.054317  
2    -0.118559  0.177899  0.100699  0.808529 -0.848933  0.180637 -0.049118  
3    -0.036788 -0.012892  0.640011 -0.485366 -0.848649  0.181935 -0.047663  
4     0.123320  0.122542  0.693578 -0.615971 -0.847865  0.185151 -0.043892  
...        ...       ...       ...       ...       ...       ...       ...  
7347 -0.190437  0.829718  0.206972 -0.425619 -0.791883  0.238604  0.049819  
7348  0.064907  0.875679 -0.879033  0.400219 -0.771840  0.252676  0.050053  
7349  0.052806 -0.266724  0.864404  0.701169 -0.779133  0.249145  0.040811  
7350 -0.101360  0.700740  0.936674 -0.589479 -0.785181  0.246432  0.025339  
7351 -0.280088 -0.007739 -0.056088 -0.616956 -0.783267  0.246809  0.036695  

[7352 rows x 561 columns]

In [4]:
targets = []
with open('y_train.txt') as inputfile2:
    for row in csv.reader(inputfile2):
        targets.append([float(i) for i in re.sub("\s+",",",row[0].strip()).split(",")])

In [5]:
y = pd.DataFrame(targets)
y

0
0     5.0
1     5.0
2     5.0
3     5.0
4     5.0
...   ...
7347  2.0
7348  2.0
7349  2.0
7350  2.0
7351  2.0

[7352 rows x 1 columns]

## Task 1: Create Binary target variable: categories 1,2,3 --> 1, categories 4,5,6 --> 0 
This will represent binary variable indicating if person is walking or not

In [6]:
y.loc[y[0].isin([1, 2, 3]), 0] = 1
y.loc[y[0].isin([4, 5, 6]), 0] = 0

In [7]:
y

0
0     0.0
1     0.0
2     0.0
3     0.0
4     0.0
...   ...
7347  1.0
7348  1.0
7349  1.0
7350  1.0
7351  1.0

[7352 rows x 1 columns]

## Task 2

+ Create Univariate Binary Logistic Regression with feature number 54, which represents `tGravityAcc-min()-Y`: gravity acceleration signals in direction of Y
+ Compare the results of Logistic regressions from different Python packages (sklearn, statsmodel)
+ Plot the FIT of predicted probabilities to the original values

In [8]:
X_univ = X.loc[:,54]
X_univ = sm.add_constant(X_univ)

In [9]:
X_univ_train, X_univ_test, y_train, y_test = train_test_split(X_univ, y, train_size = 0.8, test_size = 0.2)

Using sklearn

In [10]:
log_reg = LogisticRegression()
log_reg.fit(X_univ_train, y_train)
y_pred = log_reg.predict(X_univ_test)

C:\Users\Phillipe\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


In [11]:
y_pred

array([0., 0., 1., ..., 0., 1., 1.])

In [12]:
cnf_matrix = metrics.confusion_matrix(y_test, y_pred)
cnf_matrix

array([[598, 203],
       [220, 450]], dtype=int64)

In [13]:
metrics.accuracy_score(y_test, y_pred)

0.7124405166553365

Using statsmodels

In [14]:
log_reg2 = sm.Logit(y_train, X_univ_train).fit()
y_pred2 = log_reg2.predict(X_univ_test)
thres = 0.5
y_pred2 = [int(value > thres) for value in y_pred2]

Optimization terminated successfully.
         Current function value: 0.548505
         Iterations 6


In [15]:
cnf_matrix = metrics.confusion_matrix(y_test, y_pred2)
cnf_matrix

array([[598, 203],
       [219, 451]], dtype=int64)

In [16]:
metrics.accuracy_score(y_test, y_pred2)

0.7131203263086335

We can see that both packages gives us identical solutions, taking into account the randomness of the selected training sets and other randomness factors.

## Task 3
- Try to fit Binary Logistic Regression with all the features? How many are significant?

In [17]:
X = sm.add_constant(X)
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size = 0.8, test_size = 0.2)

In [21]:
X_train

const         0         1         2         3         4         5  \
4477    1.0  0.306059 -0.001526 -0.122492 -0.067882  0.116780 -0.248007   
665     1.0  0.299202  0.000889 -0.089378 -0.316590 -0.135520 -0.450582   
382     1.0  0.270556 -0.006125 -0.091966 -0.994587 -0.971235 -0.981706   
2085    1.0  0.287934 -0.030863 -0.101530 -0.990517 -0.873569 -0.967539   
957     1.0  0.245974 -0.031891 -0.082637  0.319143  0.217927 -0.282917   
...     ...       ...       ...       ...       ...       ...       ...   
4589    1.0  0.271961 -0.019885 -0.069584 -0.961967 -0.888776 -0.884055   
2726    1.0  0.272946 -0.026206 -0.097924 -0.991364 -0.943502 -0.982904   
1905    1.0  0.272672 -0.014362 -0.105300 -0.996273 -0.967491 -0.990088   
6845    1.0  0.278451 -0.017493 -0.108826 -0.997396 -0.988246 -0.995894   
7192    1.0  0.280906 -0.079616 -0.208775 -0.982033 -0.806218 -0.756311   

             6         7         8  ...       551       552       553  \
4477 -0.072135 -0.089027 -0.259189  ...  0.485393  0.573072  0.376569   
665  -0.363769 -0.153320 -0.412733  ... -0.115780  0.008102 -0.340434   
382  -0.995485 -0.973628 -0.982279  ...  0.113795 -0.525067 -0.857064   
2085 -0.991867 -0.866622 -0.964456  ...  0.500713 -0.490854 -0.768323   
957   0.205768  0.143761 -0.363199  ... -0.054191 -0.411298 -0.796306   
...        ...       ...       ...  ...       ...       ...       ...   
4589 -0.973663 -0.913243 -0.884899  ... -0.218202 -0.225573 -0.584807   
2726 -0.992612 -0.940185 -0.983258  ... -0.040222 -0.397822 -0.774672   
1905 -0.996520 -0.967007 -0.989373  ...  0.582656 -0.929331 -0.983238   
6845 -0.997382 -0.988492 -0.996205  ...  0.598098 -0.783790 -0.955190   
7192 -0.987001 -0.796020 -0.718654  ... -0.000253  0.345593  0.072237   

           554       555       556       557       558       559       560  
4477 -0.206140 -0.191134  0.028665  0.537481 -0.771100  0.246353 -0.039113  
665   0.022118 -0.387526 -0.884118 -0.839838 -0.595379  0.344479  0.149740  
382   0.019601 -0.098667  0.295618 -0.146840 -0.785573  0.083603 -0.137576  
2085  0.082571 -0.136581  0.057954 -0.123426 -0.550496 -0.209700 -0.043139  
957   0.280077  0.678856  0.930678 -0.678615 -0.901966  0.161446 -0.007843  
...        ...       ...       ...       ...       ...       ...       ...  
4589  0.004294  0.148213 -0.055767  0.025825 -0.874982  0.044080 -0.056103  
2726  0.001787 -0.000998  0.701185 -0.759881 -0.812518  0.225955 -0.004362  
1905  0.333798 -0.163007  0.598612 -0.812082 -0.741245  0.202514 -0.132880  
6845 -0.234263  0.014677  0.320749  0.425378 -0.740639  0.014109 -0.149106  
7192 -0.020545  0.132512 -0.728601 -0.540321 -0.908305  0.154135 -0.013660  

[5881 rows x 562 columns]

In [20]:
y

0
0     0.0
1     0.0
2     0.0
3     0.0
4     0.0
...   ...
7347  1.0
7348  1.0
7349  1.0
7350  1.0
7351  1.0

[7352 rows x 1 columns]

In [33]:
import statsmodels.api as sm
model = sm.Logit(y, X_opt)
result = model.fit()

Optimization terminated successfully.
         Current function value: 0.034993
         Iterations 11


In [30]:
import numpy as np

In [32]:
X_opt = np.array(X.loc[:, [0, 1, 2, 3, 4, 5]], dtype=float)